# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb',
                'doc_host': 'https://daphn3k.github.io',
                'git_url': 'https://github.com/daphn3k/nb',
                'lib_path': 'nb'},
  'syms': {'nb.core': {'nb.core.foo': ('core.html#foo', 'nb/core.py')}}}
